const express = require('express')
const productos = require('./Admin/Productos')
const tipoProductos = require('./Admin/TipoProductos')
const allUser = require('./Admin/User')
const UserProducts = require('./User/Products')
const register = require('./Auth/Auth')
const users = require('./User/Users')
const orderUser = require('./User/Order')
const banner = require('./Admin/Banner')
const categories = require('./User/TipeProducts')
const carrito = require('./User/Carrito')
const favorite= require('./User/favoritos')
const address = require('./User/Address')
const question= require('./Questions/productQuestionRoutes')
const suscripciones = require('./User/suscripciones')
const planes = require('./Planes/planes')   
const vendedor = require('./Seller/vendedor')
const vendedorProductos= require("./Seller/productos.vendedor")
const orders = require('./Admin/Orders')
const vendedorid = require('./User/vendedorId')
const notificacion= require('./Notificaciones/notificacion')
// const notificacionesUser = require('./User/notificaciones') 
const calificaciones = require('./Calificaciones/reviews')
const dashboardSeller = require('./Seller/dashboard')
const messages = require('./Messages/messages') 
const store = require('./Store/store')
const sellerPago = require('./Admin/sellerPago') 
const validarPago = require('./Admin/validate-payment')
const verification = require('./Seller/verificacion')
const reportar = require('./User/Report')
const reportes =require('./Admin/reportadmin') // ver reportes vendedores solo admin
const valiateIdentidad =require('./Seller/submitIdentity')


const router = express();

router.use(productos)
router.use(tipoProductos)
router.use(allUser)
router.use(UserProducts)
router.use(register)
router.use(users)
router.use(orderUser)
router.use(banner)
router.use(categories)
router.use(carrito)
router.use(favorite)
router.use(address)
router.use(question)
router.use(suscripciones)
router.use(planes)
router.use(vendedor)
router.use(vendedorProductos)
router.use(orders)
router.use(vendedorid)
router.use(notificacion)
// router.use(notificacionesUser)
router.use(calificaciones)
router.use(dashboardSeller)
router.use(messages)
router.use(store)
router.use(sellerPago)
router.use(validarPago)
router.use(verification)
router.use(reportar)
router.use(reportes)
router.use(valiateIdentidad)



module.exports = router;